# Generated by Django 3.1.7 on 2022-10-31 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='password',
        ),
    ]
